version: "3"

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}

services:
  
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: fastorder_local_django
    depends_on:
      - postgres
    volumes:
      - .:/app
    env_file:
      - ./config/settings/.env
    ports:
      - "8000:8000"
    command: /start

  postgres:
    image: postgres
    container_name: fastorder_postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
      - local_postgres_data_backups:/backups
    env_file:
      - ./config/settings/.env
