# Generated by Django 3.1.6 on 2021-04-03 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was last modified.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('comments', models.TextField(blank=True, max_length=500)),
                ('bebida', models.ManyToManyField(to='menus.Bebida')),
                ('platillo', models.ManyToManyField(to='menus.Platillo')),
                ('postre', models.ManyToManyField(to='menus.Postre')),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
    ]
